### ISSUE TITLE
Use case for this?

### ISSUE THREAD

**Issue by charles-thompson-salesforce-com** [rsoesemann/apex-unified-logging#1]
Hi,

I really appreciate the work that has gone into this.  Great effort, and it looks like a good tool.

It's not obvious what the use case for this is, and why you would use it over the [Salesforce Application Logging Framework](https://github.com/SalesforceCloudServices/Application-Logging-Framework).

Really what I'm asking for is a set of pros and cons for this approach - and I think they should be in the Readme for this project.

Many of us understand the benefits of PE, that it's designed to produce a stream of useful events for a consumer to do something with.  In the case of application logs, this would be to store the data somewhere so it can be reviewed if there is an issue (forensics) or audit.  In both cases, the life of a simple platform event is not long enough, so a more permanent storage facility is required.

Many tools and products exist, "on platform" (custom objects, Big Objects, Heroku) and off.  But unless the other half of the logging solution is built or purchased, you have only a partial tool here.  It fires and forgets (except for your nice little monitoring component).

**Comment by rsoesemann** [comment]
This is not a product and doesn't compete with anything out there. It was meant as a showcase on how to overcome the limitations of the current logging and it was well received by some experts out there. Open Source projects can exist side by side and the best one for is the one you pick.

To be honest I don't want to invest time comparing projects for you but feel free to reach out with more concrete questions.
