### ISSUE TITLE
App does not have any navigation items

### ISSUE THREAD

**Issue by twentyTwo** [rsoesemann/apex-unified-logging#2]
I have deploy the code from github and assign the app permission to the system admin profile. I am getting the app but the app does not have any navigation item.

Can you please help in this regard? @rsoesemann 

![image](https://user-images.githubusercontent.com/4258676/74821757-49cd1700-532e-11ea-8de6-3160993d3108.png)

**Comment by rsoesemann** [comment]
It’s doesn’t need navigation item. It’s only ui is a console app.

**Comment by rsoesemann** [comment]
@twentyTwo I will close this now. Feel free to comment and I can reopen it.
