### ISSUE TITLE
Log monitor not showing values

### ISSUE THREAD

**Issue by ofarras** [rsoesemann/apex-unified-logging#6]
Log monitor (lwc) was not showing values event events are generated correctly :(

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/63863115/165087099-d98de41a-5323-4939-a10f-94291e66ab88.png">

**Comment by rsoesemann** [comment]
Do you have a fork where you and maybe I can reproduce that?

Are you getting any log errorS?

**Comment by ofarras** [comment]
Robert I've added a new fork and requested you a pull request with change to resolve this.

Best regards

**Comment by rsoesemann** [comment]
Fix in https://github.com/rsoesemann/apex-unified-logging/pull/7
